export const CHANGE_POST = "CHANGE_POST";
export const GET_POST_BY_ID = "GET_POST_BY_ID";

export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST" ;
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS" ;
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE" ;